name: WW Docker Build Action
description: Build & push docker images from ww-versions.yml
author: Sut3kh
branding:
  color: orange
  icon: anchor

runs:
  using: docker
  image: Dockerfile

inputs:
  registry:
    description: Docker registry
    required: false
    default: "docker.pkg.github.com"
  repository:
    description: Docker repository
    required: true
  username:
    description: Docker registry username
    required: false
  password:
    description: Docker registry password
    required: false
  push:
    description: Push to registry
    required: false
    default: "1"
  path:
    description: "The path to ww-versions.yml in the repo."
    required: false
    default: "."
  build_args:
    description: "Build arguments to pass to docker build (yaml key/value pairs)."
    required: false
    default: ""
